<?php
/**
 * WooShop Asset Configuration.
 *
 * Defines global, component, page, editor, and WooCommerce assets.
 *
 * Asset paths correspond directly to the files generated by the
 * WooShop build system.
 *
 * @package WooShop
 */

defined( 'ABSPATH' ) || exit;

return array(

    /*
     * ---------------------------------------------------------
     * Global Styles
     * ---------------------------------------------------------
     *
     * These styles are available to the entire theme.
     */
    'styles' => array(

        /*
         * Bootstrap core.
         */
        'bootstrap' => array(
            'src'     => 'assets/build/css/bootstrap.min.css',
            'deps'    => array(),
            'version' => null,
            'media'   => 'all',
        ),

        /*
         * WooShop application stylesheet.
         *
         * Contains theme-level styles and selected Bootstrap
         * components compiled through the SCSS build system.
         */
        'app' => array(
            'src'     => 'assets/build/css/app.min.css',
            'deps'    => array( 'bootstrap' ),
            'version' => null,
            'media'   => 'all',
        ),
    ),

    /*
     * ---------------------------------------------------------
     * Component Styles
     * ---------------------------------------------------------
     *
     * Components are loaded only when required.
     */
    'components' => array(

        'header' => array(
            'src'     => 'assets/build/css/components/header.min.css',
            'deps'    => array( 'app' ),
            'version' => null,
            'media'   => 'all',
        ),

        'branding' => array(
            'src'     => 'assets/build/css/components/branding.min.css',
            'deps'    => array( 'app' ),
            'version' => null,
            'media'   => 'all',
        ),

        'navigation' => array(
            'src'     => 'assets/build/css/components/navigation.min.css',
            'deps'    => array( 'app' ),
            'version' => null,
            'media'   => 'all',
        ),

        'categories' => array(
            'src'     => 'assets/build/css/components/categories.min.css',
            'deps'    => array( 'app' ),
            'version' => null,
            'media'   => 'all',
        ),

        'footer' => array(
            'src'     => 'assets/build/css/components/footer.min.css',
            'deps'    => array( 'app' ),
            'version' => null,
            'media'   => 'all',
        ),

        'carousel' => array(
            'src'     => 'assets/build/css/components/carousel.min.css',
            'deps'    => array( 'app' ),
            'version' => null,
            'media'   => 'all',
        ),
    ),

    /*
     * ---------------------------------------------------------
     * Page Styles
     * ---------------------------------------------------------
     *
     * Loaded according to the current WordPress page context.
     */
    'pages' => array(

        'front-page' => array(
            'src'     => 'assets/build/css/pages/front-page.min.css',
            'deps'    => array( 'app' ),
            'version' => null,
            'media'   => 'all',
        ),

        'home' => array(
            'src'     => 'assets/build/css/pages/home.min.css',
            'deps'    => array( 'app' ),
            'version' => null,
            'media'   => 'all',
        ),

        'page' => array(
            'src'     => 'assets/build/css/pages/page.min.css',
            'deps'    => array( 'app' ),
            'version' => null,
            'media'   => 'all',
        ),

        'single' => array(
            'src'     => 'assets/build/css/pages/single.min.css',
            'deps'    => array( 'app' ),
            'version' => null,
            'media'   => 'all',
        ),

        'archive' => array(
            'src'     => 'assets/build/css/pages/archive.min.css',
            'deps'    => array( 'app' ),
            'version' => null,
            'media'   => 'all',
        ),

        'search' => array(
            'src'     => 'assets/build/css/pages/search.min.css',
            'deps'    => array( 'app' ),
            'version' => null,
            'media'   => 'all',
        ),

        '404' => array(
            'src'     => 'assets/build/css/pages/404.min.css',
            'deps'    => array( 'app' ),
            'version' => null,
            'media'   => 'all',
        ),
    ),

    /*
     * ---------------------------------------------------------
     * Editor Styles
     * ---------------------------------------------------------
     */
    'editor' => array(

        'styles' => array(

            'editor' => array(
                'src'     => 'assets/build/css/editor.min.css',
                'deps'    => array(),
                'version' => null,
                'media'   => 'all',
            ),
        ),

        'scripts' => array(),
    ),

    /*
     * ---------------------------------------------------------
     * Global Scripts
     * ---------------------------------------------------------
     */
    'scripts' => array(

        'bootstrap' => array(
            'src'       => 'assets/build/js/bootstrap.bundle.min.js',
            'deps'      => array(),
            'version'   => null,
            'in_footer' => true,
        ),

        'app' => array(
            'src'       => 'assets/build/js/app.min.js',
            'deps'      => array( 'bootstrap' ),
            'version'   => null,
            'in_footer' => true,
        ),
    ),

    /*
     * ---------------------------------------------------------
     * Component Scripts
     * ---------------------------------------------------------
     */
    'component_scripts' => array(

        'carousel' => array(
            'src'       => 'assets/build/js/components/carousel.min.js',
            'deps'      => array( 'app' ),
            'version'   => null,
            'in_footer' => true,
        ),

        'navigation' => array(
            'src'       => 'assets/build/js/components/navigation.min.js',
            'deps'      => array( 'app' ),
            'version'   => null,
            'in_footer' => true,
        ),
    ),

    /*
     * ---------------------------------------------------------
     * Page Scripts
     * ---------------------------------------------------------
     */
    'page_scripts' => array(

        'front-page' => array(
            'src'       => 'assets/build/js/pages/front-page.min.js',
            'deps'      => array( 'app' ),
            'version'   => null,
            'in_footer' => true,
        ),

        'single' => array(
            'src'       => 'assets/build/js/pages/single.min.js',
            'deps'      => array( 'app' ),
            'version'   => null,
            'in_footer' => true,
        ),
    ),

    /*
	 * =========================================================
	 * WOOCOMMERCE ASSETS
	 * =========================================================
	 */
    'woocommerce' => array(

        /*
         * -----------------------------------------------------
         * Global WooCommerce Styles
         * -----------------------------------------------------
         */
        'styles' => array(

            'woocommerce' => array(
                'src'     => 'assets/build/css/woocommerce.min.css',
                'deps'    => array( 'app' ),
                'version' => null,
                'media'   => 'all',
            ),
        ),

        /*
         * -----------------------------------------------------
         * Global WooCommerce Scripts
         * -----------------------------------------------------
         */
        'scripts' => array(

            'woocommerce' => array(
                'src'       => 'assets/build/js/woocommerce.min.js',
                'deps'      => array( 'app' ),
                'version'   => null,
                'in_footer' => true,
            ),
        ),

        /*
         * -----------------------------------------------------
         * WooCommerce Components
         * -----------------------------------------------------
         */
        'components' => array(

            'product-card' => array(
                'src'     => 'assets/build/css/woocommerce/product-card.min.css',
                'deps'    => array( 'woocommerce' ),
                'version' => null,
                'media'   => 'all',
            ),

            'product-gallery' => array(
                'src'     => 'assets/build/css/woocommerce/product-gallery.min.css',
                'deps'    => array( 'woocommerce' ),
                'version' => null,
                'media'   => 'all',
            ),

            'cart' => array(
                'src'     => 'assets/build/css/woocommerce/cart.min.css',
                'deps'    => array( 'woocommerce' ),
                'version' => null,
                'media'   => 'all',
            ),

            'checkout' => array(
                'src'     => 'assets/build/css/woocommerce/checkout.min.css',
                'deps'    => array( 'woocommerce' ),
                'version' => null,
                'media'   => 'all',
            ),

            'account' => array(
                'src'     => 'assets/build/css/woocommerce/account.min.css',
                'deps'    => array( 'woocommerce' ),
                'version' => null,
                'media'   => 'all',
            ),

            'product-archive' => array(
                'src'     => 'assets/build/css/woocommerce/product-archive.min.css',
                'deps'    => array( 'woocommerce' ),
                'version' => null,
                'media'   => 'all',
            ),

            'single-product' => array(
                'src'     => 'assets/build/css/woocommerce/single-product.min.css',
                'deps'    => array( 'woocommerce' ),
                'version' => null,
                'media'   => 'all',
            ),
        ),

        /*
         * -----------------------------------------------------
         * WooCommerce Feature Assets
         * -----------------------------------------------------
         */
        'features' => array(

            'mini-cart' => array(
                'style' => array(
                    'src'     => 'assets/build/css/woocommerce/features/mini-cart.min.css',
                    'deps'    => array( 'woocommerce' ),
                    'version' => null,
                    'media'   => 'all',
                ),
                'script' => array(
                    'src'       => 'assets/build/js/woocommerce/features/mini-cart.min.js',
                    'deps'      => array( 'woocommerce' ),
                    'version'   => null,
                    'in_footer' => true,
                ),
            ),

            'quick-view' => array(
                'style' => array(
                    'src'     => 'assets/build/css/woocommerce/features/quick-view.min.css',
                    'deps'    => array( 'woocommerce' ),
                    'version' => null,
                    'media'   => 'all',
                ),
                'script' => array(
                    'src'       => 'assets/build/js/woocommerce/features/quick-view.min.js',
                    'deps'      => array( 'woocommerce' ),
                    'version'   => null,
                    'in_footer' => true,
                ),
            ),

            'swatches' => array(
                'style' => array(
                    'src'     => 'assets/build/css/woocommerce/features/swatches.min.css',
                    'deps'    => array( 'woocommerce' ),
                    'version' => null,
                    'media'   => 'all',
                ),
                'script' => array(
                    'src'       => 'assets/build/js/woocommerce/features/swatches.min.js',
                    'deps'      => array( 'woocommerce' ),
                    'version'   => null,
                    'in_footer' => true,
                ),
            ),

            'product-filters' => array(
                'style' => array(
                    'src'     => 'assets/build/css/woocommerce/features/product-filters.min.css',
                    'deps'    => array( 'woocommerce' ),
                    'version' => null,
                    'media'   => 'all',
                ),
                'script' => array(
                    'src'       => 'assets/build/js/woocommerce/features/product-filters.min.js',
                    'deps'      => array( 'woocommerce' ),
                    'version'   => null,
                    'in_footer' => true,
                ),
            ),

            'wishlist' => array(
                'style' => array(
                    'src'     => 'assets/build/css/woocommerce/features/wishlist.min.css',
                    'deps'    => array( 'woocommerce' ),
                    'version' => null,
                    'media'   => 'all',
                ),
                'script' => array(
                    'src'       => 'assets/build/js/woocommerce/features/wishlist.min.js',
                    'deps'      => array( 'woocommerce' ),
                    'version'   => null,
                    'in_footer' => true,
                ),
            ),

            'compare' => array(
                'style' => array(
                    'src'     => 'assets/build/css/woocommerce/features/compare.min.css',
                    'deps'    => array( 'woocommerce' ),
                    'version' => null,
                    'media'   => 'all',
                ),
                'script' => array(
                    'src'       => 'assets/build/js/woocommerce/features/compare.min.js',
                    'deps'      => array( 'woocommerce' ),
                    'version'   => null,
                    'in_footer' => true,
                ),
            ),

            'brands' => array(
                'style' => array(
                    'src'     => 'assets/build/css/woocommerce/features/brands.min.css',
                    'deps'    => array( 'woocommerce' ),
                    'version' => null,
                    'media'   => 'all',
                ),
            ),

            'reviews' => array(
                'style' => array(
                    'src'     => 'assets/build/css/woocommerce/features/reviews.min.css',
                    'deps'    => array( 'woocommerce' ),
                    'version' => null,
                    'media'   => 'all',
                ),
                'script' => array(
                    'src'       => 'assets/build/js/woocommerce/features/reviews.min.js',
                    'deps'      => array( 'woocommerce' ),
                    'version'   => null,
                    'in_footer' => true,
                ),
            ),

            'size-guide' => array(
                'style' => array(
                    'src'     => 'assets/build/css/woocommerce/features/size-guide.min.css',
                    'deps'    => array( 'woocommerce' ),
                    'version' => null,
                    'media'   => 'all',
                ),
                'script' => array(
                    'src'       => 'assets/build/js/woocommerce/features/size-guide.min.js',
                    'deps'      => array( 'woocommerce' ),
                    'version'   => null,
                    'in_footer' => true,
                ),
            ),

            'product-tabs' => array(
                'style' => array(
                    'src'     => 'assets/build/css/woocommerce/features/product-tabs.min.css',
                    'deps'    => array( 'woocommerce' ),
                    'version' => null,
                    'media'   => 'all',
                ),
                'script' => array(
                    'src'       => 'assets/build/js/woocommerce/features/product-tabs.min.js',
                    'deps'      => array( 'woocommerce' ),
                    'version'   => null,
                    'in_footer' => true,
                ),
            ),

            'product-video' => array(
                'style' => array(
                    'src'     => 'assets/build/css/woocommerce/features/product-video.min.css',
                    'deps'    => array( 'woocommerce' ),
                    'version' => null,
                    'media'   => 'all',
                ),
                'script' => array(
                    'src'       => 'assets/build/js/woocommerce/features/product-video.min.js',
                    'deps'      => array( 'woocommerce' ),
                    'version'   => null,
                    'in_footer' => true,
                ),
            ),

            'countdown' => array(
                'style' => array(
                    'src'     => 'assets/build/css/woocommerce/features/countdown.min.css',
                    'deps'    => array( 'woocommerce' ),
                    'version' => null,
                    'media'   => 'all',
                ),
                'script' => array(
                    'src'       => 'assets/build/js/woocommerce/features/countdown.min.js',
                    'deps'      => array( 'woocommerce' ),
                    'version'   => null,
                    'in_footer' => true,
                ),
            ),

            'shipping-bar' => array(
                'style' => array(
                    'src'     => 'assets/build/css/woocommerce/features/shipping-bar.min.css',
                    'deps'    => array( 'woocommerce' ),
                    'version' => null,
                    'media'   => 'all',
                ),
                'script' => array(
                    'src'       => 'assets/build/js/woocommerce/features/shipping-bar.min.js',
                    'deps'      => array( 'woocommerce' ),
                    'version'   => null,
                    'in_footer' => true,
                ),
            ),

            'stock' => array(
                'style' => array(
                    'src'     => 'assets/build/css/woocommerce/features/stock.min.css',
                    'deps'    => array( 'woocommerce' ),
                    'version' => null,
                    'media'   => 'all',
                ),
            ),

            'waitlist' => array(
                'style' => array(
                    'src'     => 'assets/build/css/woocommerce/features/waitlist.min.css',
                    'deps'    => array( 'woocommerce' ),
                    'version' => null,
                    'media'   => 'all',
                ),
                'script' => array(
                    'src'       => 'assets/build/js/woocommerce/features/waitlist.min.js',
                    'deps'      => array( 'woocommerce' ),
                    'version'   => null,
                    'in_footer' => true,
                ),
            ),

            'social-share' => array(
                'style' => array(
                    'src'     => 'assets/build/css/woocommerce/features/social-share.min.css',
                    'deps'    => array( 'woocommerce' ),
                    'version' => null,
                    'media'   => 'all',
                ),
            ),

            'payment-icons' => array(
                'style' => array(
                    'src'     => 'assets/build/css/woocommerce/features/payment-icons.min.css',
                    'deps'    => array( 'woocommerce' ),
                    'version' => null,
                    'media'   => 'all',
                ),
            ),

            'mobile' => array(
                'style' => array(
                    'src'     => 'assets/build/css/woocommerce/features/mobile.min.css',
                    'deps'    => array( 'woocommerce' ),
                    'version' => null,
                    'media'   => 'all',
                ),
                'script' => array(
                    'src'       => 'assets/build/js/woocommerce/features/mobile.min.js',
                    'deps'      => array( 'woocommerce' ),
                    'version'   => null,
                    'in_footer' => true,
                ),
            ),
        ),
    ),
);