<?php
/**
 * WooShop Asset Configuration
 *
 * Defines global, component, page, and WooCommerce assets.
 *
 * Asset paths correspond directly to the files generated by build.js.
 * Components are loaded independently so pages only receive the assets
 * they actually require.
 *
 * @package WooShop
 */

defined( 'ABSPATH' ) || exit;

return array(

    /*
     * Global styles.
     */
    'styles' => array(

        'bootstrap' => array(
            'src'     => 'assets/build/css/bootstrap.min.css',
            'css_deps'    => array(),
            'version' => null,
            'media'   => 'all',
        ),

        'app' => array(
            'src'     => 'assets/build/css/app.min.css',
            'css_deps'    => array( 'bootstrap' ),
            'version' => null,
            'media'   => 'all',
        ),

    ),

    /*
     * Global scripts.
     */
    'scripts' => array(

        'bootstrap' => array(
            'src'       => 'assets/build/js/bootstrap.bundle.min.js',
            'js_deps'      => array(),
            'version'   => null,
            'in_footer' => true,
        ),

        'app' => array(
            'src'       => 'assets/build/js/app.min.js',
            'js_deps'      => array( 'bootstrap' ),
            'version'   => null,
            'in_footer' => true,
        ),

    ),

    /*
     * Component styles.
     *
     * These are loaded only when requested by a module.
     */
    'components' => array(

        'accessibility' => array(
            'css' => 'assets/build/css/components/accessibility.min.css',
        ),

        'compare' => array(
            'css' => 'assets/build/css/components/compare.min.css',
            'js'  => 'assets/build/js/components/compare.min.js',
        ),

        'free-shipping-bar' => array(
            'css' => 'assets/build/css/components/free-shipping-bar.min.css',
            'js'  => 'assets/build/js/components/free-shipping-bar.min.js',
        ),

        'mini-cart' => array(
            'css' => 'assets/build/css/components/mini-cart.min.css',
            'js'  => 'assets/build/js/components/mini-cart.min.js',
        ),

        'mobile-commerce' => array(
            'css' => 'assets/build/css/components/mobile-commerce.min.css',
            'js'  => 'assets/build/js/components/mobile-commerce.min.js',
        ),

        'mobile-sales' => array(
            'css' => 'assets/build/css/components/mobile-sales.min.css',
            'js'  => 'assets/build/js/components/mobile-sales.min.js',
        ),

        'payment-icons' => array(
            'css' => 'assets/build/css/components/payment-icons.min.css',
            'js'  => 'assets/build/js/components/payment-icons.min.js',
        ),

        'product-brands' => array(
            'css' => 'assets/build/css/components/product-brands.min.css',
            'js'  => 'assets/build/js/components/product-brands.min.js',
        ),

        'product-custom-tabs' => array(
            'css' => 'assets/build/css/components/product-custom-tabs.min.css',
            'js'  => 'assets/build/js/components/product-custom-tabs.min.js',
        ),

        'product-filters' => array(
            'css' => 'assets/build/css/components/product-filters.min.css',
            'js'  => 'assets/build/js/components/product-filters.min.js',
        ),

        'product-search' => array(
            'css' => 'assets/build/css/components/product-search.min.css',
            'js'  => 'assets/build/js/components/product-search.min.js',
        ),

        'product-videos' => array(
            'css' => 'assets/build/css/components/product-videos.min.css',
            'js'  => 'assets/build/js/components/product-videos.min.js',
        ),

        'product-waitlist' => array(
            'css' => 'assets/build/css/components/product-waitlist.min.css',
            'js'  => 'assets/build/js/components/product-waitlist.min.js',
        ),

        'quick-view' => array(
            'css' => 'assets/build/css/components/quick-view.min.css',
            'js'  => 'assets/build/js/components/quick-view.min.js',
        ),

        'reviews' => array(
            'css' => 'assets/build/css/components/reviews.min.css',
            'js'  => 'assets/build/js/components/reviews.min.js',
        ),

        'sale-countdown' => array(
            'css' => 'assets/build/css/components/sale-countdown.min.css',
            'js'  => 'assets/build/js/components/sale-countdown.min.js',
        ),

        'size-guide' => array(
            'css' => 'assets/build/css/components/size-guide.min.css',
            'js'  => 'assets/build/js/components/size-guide.min.js',
        ),

        'social-sharing' => array(
            'css' => 'assets/build/css/components/social-sharing.min.css',
            'js'  => 'assets/build/js/components/social-sharing.min.js',
        ),

        'stock-scarcity' => array(
            'css' => 'assets/build/css/components/stock-scarcity.min.css',
            'js'  => 'assets/build/js/components/stock-scarcity.min.js',
        ),

        'variation-swatches' => array(
            'css' => 'assets/build/css/components/variation-swatches.min.css',
            'js'  => 'assets/build/js/components/variation-swatches.min.js',
        ),

        'wishlist' => array(
            'css' => 'assets/build/css/components/wishlist.min.css',
            'js'  => 'assets/build/js/components/wishlist.min.js',
        ),

    ),

    /*
     * ---------------------------------------------------------
     * WooCommerce Assets
     * ---------------------------------------------------------
     */

    'woocommerce' => array(

        'base' => array(
            'css' => 'assets/build/css/woocommerce.min.css',
        ),

        'product' => array(
            'css' => 'assets/build/css/woocommerce/product.min.css',
            'js'  => 'assets/build/js/woocommerce/product.min.js',
        ),

        'product-card' => array(
            'css' => 'assets/build/css/woocommerce/product-card.min.css',
        ),

        'shop' => array(
            'css' => 'assets/build/css/woocommerce/shop.min.css',
            'js'  => 'assets/build/js/woocommerce/shop.min.js',
        ),

        'cart' => array(
            'css' => 'assets/build/css/woocommerce/cart.min.css',
            'js'  => 'assets/build/js/woocommerce/cart.min.js',
        ),

        'checkout' => array(
            'css' => 'assets/build/css/woocommerce/checkout.min.css',
            'js'  => 'assets/build/js/woocommerce/checkout.min.js',
        ),

        'account' => array(
            'css' => 'assets/build/css/woocommerce/account.min.css',
            'js'  => 'assets/build/js/woocommerce/account.min.js',
        ),

    ),

);

//return array(
//
//    /*
//     * ---------------------------------------------------------
//     * Global Styles
//     * ---------------------------------------------------------
//     */
//
//    'styles' => array(
//
//        /*
//         * Main WooShop stylesheet.
//         *
//         * Contains the selected Bootstrap CSS components and
//         * global WooShop foundation/layout styles.
//         */
//        'wooshop-app' => array(
//            'src'  => 'assets/build/css/app.min.css',
//            'deps' => array(),
//        ),
//
//    ),
//
//    /*
//     * ---------------------------------------------------------
//     * Global Scripts
//     * ---------------------------------------------------------
//     */
//
//    'scripts' => array(
//
//        /*
//         * Main WooShop JavaScript.
//         *
//         * Contains only globally required Bootstrap JavaScript
//         * components and global WooShop JavaScript.
//         */
//        'wooshop-app' => array(
//            'src'       => 'assets/build/js/app.min.js',
//            'deps'      => array(),
//            'in_footer' => true,
//        ),
//
//    ),
//
//    /*
//     * ---------------------------------------------------------
//     * Component Styles
//     * ---------------------------------------------------------
//     *
//     * Each component has an independent CSS file.
//     */
//
//    'components' => array(
//
//        'accessibility' => array(
//            'src' => 'assets/build/css/components/accessibility.min.css',
//        ),
//
//        'compare' => array(
//            'src' => 'assets/build/css/components/compare.min.css',
//        ),
//
//        'free-shipping-bar' => array(
//            'src' => 'assets/build/css/components/free-shipping-bar.min.css',
//        ),
//
//        'mini-cart' => array(
//            'src' => 'assets/build/css/components/mini-cart.min.css',
//        ),
//
//        'mobile-commerce' => array(
//            'src' => 'assets/build/css/components/mobile-commerce.min.css',
//        ),
//
//        'mobile-sales' => array(
//            'src' => 'assets/build/css/components/mobile-sales.min.css',
//        ),
//
//        'payment-icons' => array(
//            'src' => 'assets/build/css/components/payment-icons.min.css',
//        ),
//
//        'product-brands' => array(
//            'src' => 'assets/build/css/components/product-brands.min.css',
//        ),
//
//        'product-custom-tabs' => array(
//            'src' => 'assets/build/css/components/product-custom-tabs.min.css',
//        ),
//
//        'product-filters' => array(
//            'src' => 'assets/build/css/components/product-filters.min.css',
//        ),
//
//        'product-search' => array(
//            'src' => 'assets/build/css/components/product-search.min.css',
//        ),
//
//        'product-videos' => array(
//            'src' => 'assets/build/css/components/product-videos.min.css',
//        ),
//
//        'product-waitlist' => array(
//            'src' => 'assets/build/css/components/product-waitlist.min.css',
//        ),
//
//        'quick-view' => array(
//            'src' => 'assets/build/css/components/quick-view.min.css',
//        ),
//
//        'reviews' => array(
//            'src' => 'assets/build/css/components/reviews.min.css',
//        ),
//
//        'sale-countdown' => array(
//            'src' => 'assets/build/css/components/sale-countdown.min.css',
//        ),
//
//        'size-guide' => array(
//            'src' => 'assets/build/css/components/size-guide.min.css',
//        ),
//
//        'social-sharing' => array(
//            'src' => 'assets/build/css/components/social-sharing.min.css',
//        ),
//
//        'stock-scarcity' => array(
//            'src' => 'assets/build/css/components/stock-scarcity.min.css',
//        ),
//
//        'variation-swatches' => array(
//            'src' => 'assets/build/css/components/variation-swatches.min.css',
//        ),
//
//        'wishlist' => array(
//            'src' => 'assets/build/css/components/wishlist.min.css',
//        ),
//
//    ),
//
//    /*
//     * ---------------------------------------------------------
//     * Component Scripts
//     * ---------------------------------------------------------
//     */
//
//    'component_scripts' => array(
//
//        'compare' => array(
//            'src' => 'assets/build/js/components/compare.min.js',
//        ),
//
//        'free-shipping-bar' => array(
//            'src' => 'assets/build/js/components/free-shipping-bar.min.js',
//        ),
//
//        'mini-cart' => array(
//            'src' => 'assets/build/js/components/mini-cart.min.js',
//        ),
//
//        'mobile-commerce' => array(
//            'src' => 'assets/build/js/components/mobile-commerce.min.js',
//        ),
//
//        'mobile-sales' => array(
//            'src' => 'assets/build/js/components/mobile-sales.min.js',
//        ),
//
//        'payment-icons' => array(
//            'src' => 'assets/build/js/components/payment-icons.min.js',
//        ),
//
//        'product-brands' => array(
//            'src' => 'assets/build/js/components/product-brands.min.js',
//        ),
//
//        'product-custom-tabs' => array(
//            'src' => 'assets/build/js/components/product-custom-tabs.min.js',
//        ),
//
//        'product-filters' => array(
//            'src' => 'assets/build/js/components/product-filters.min.js',
//        ),
//
//        'product-search' => array(
//            'src' => 'assets/build/js/components/product-search.min.js',
//        ),
//
//        'product-videos' => array(
//            'src' => 'assets/build/js/components/product-videos.min.js',
//        ),
//
//        'product-waitlist' => array(
//            'src' => 'assets/build/js/components/product-waitlist.min.js',
//        ),
//
//        'quick-view' => array(
//            'src' => 'assets/build/js/components/quick-view.min.js',
//        ),
//
//        'reviews' => array(
//            'src' => 'assets/build/js/components/reviews.min.js',
//        ),
//
//        'sale-countdown' => array(
//            'src' => 'assets/build/js/components/sale-countdown.min.js',
//        ),
//
//        'size-guide' => array(
//            'src' => 'assets/build/js/components/size-guide.min.js',
//        ),
//
//        'social-sharing' => array(
//            'src' => 'assets/build/js/components/social-sharing.min.js',
//        ),
//
//        'stock-scarcity' => array(
//            'src' => 'assets/build/js/components/stock-scarcity.min.js',
//        ),
//
//        'variation-swatches' => array(
//            'src' => 'assets/build/js/components/variation-swatches.min.js',
//        ),
//
//        'wishlist' => array(
//            'src' => 'assets/build/js/components/wishlist.min.js',
//        ),
//
//    ),
//
//    /*
//     * ---------------------------------------------------------
//     * WooCommerce Styles
//     * ---------------------------------------------------------
//     */
//
//    'woocommerce' => array(
//
//        'style' => array(
//            'src' => 'assets/build/css/woocommerce.min.css',
//        ),
//
//        'product' => array(
//            'src' => 'assets/build/css/woocommerce/product.min.css',
//        ),
//
//        'product-card' => array(
//            'src' => 'assets/build/css/woocommerce/product-card.min.css',
//        ),
//
//        'shop' => array(
//            'src' => 'assets/build/css/woocommerce/shop.min.css',
//        ),
//
//        'cart' => array(
//            'src' => 'assets/build/css/woocommerce/cart.min.css',
//        ),
//
//        'checkout' => array(
//            'src' => 'assets/build/css/woocommerce/checkout.min.css',
//        ),
//
//        'account' => array(
//            'src' => 'assets/build/css/woocommerce/account.min.css',
//        ),
//
//    ),
//
//    /*
//     * ---------------------------------------------------------
//     * WooCommerce Scripts
//     * ---------------------------------------------------------
//     */
//
//    'woocommerce_scripts' => array(
//
//        'product' => array(
//            'src' => 'assets/build/js/woocommerce/product.min.js',
//        ),
//
//        'shop' => array(
//            'src' => 'assets/build/js/woocommerce/shop.min.js',
//        ),
//
//        'cart' => array(
//            'src' => 'assets/build/js/woocommerce/cart.min.js',
//        ),
//
//        'checkout' => array(
//            'src' => 'assets/build/js/woocommerce/checkout.min.js',
//        ),
//
//        'account' => array(
//            'src' => 'assets/build/js/woocommerce/account.min.js',
//        ),
//
//    ),
//
//);