<?php
/**
 * WooShop Asset Configuration.
 *
 * Defines global, component, page, editor, and WooCommerce assets.
 *
 * Asset paths correspond directly to the files generated by the
 * WooShop build system.
 *
 * @package WooShop
 */

defined( 'ABSPATH' ) || exit;

return array(

    /*
     * ---------------------------------------------------------
     * Global Styles
     * ---------------------------------------------------------
     *
     * These styles are available to the entire theme.
     */
    'styles' => array(

        /*
         * Bootstrap core.
         */
        'bootstrap' => array(
            'src'     => 'assets/build/css/bootstrap.min.css',
            'deps'    => array(),
            'version' => null,
            'media'   => 'all',
        ),

        /*
         * WooShop application stylesheet.
         *
         * Contains theme-level styles and selected Bootstrap
         * components compiled through the SCSS build system.
         */
        'app' => array(
            'src'     => 'assets/build/css/app.min.css',
            'deps'    => array( 'bootstrap' ),
            'version' => null,
            'media'   => 'all',
        ),
    ),

    /*
     * ---------------------------------------------------------
     * Component Styles
     * ---------------------------------------------------------
     *
     * Components are loaded only when required.
     */
    'components' => array(

        'header' => array(
            'src'     => 'assets/build/css/components/header.min.css',
            'deps'    => array( 'app' ),
            'version' => null,
            'media'   => 'all',
        ),

        'branding' => array(
            'src'     => 'assets/build/css/components/branding.min.css',
            'deps'    => array( 'app' ),
            'version' => null,
            'media'   => 'all',
        ),

        'navigation' => array(
            'src'     => 'assets/build/css/components/navigation.min.css',
            'deps'    => array( 'app' ),
            'version' => null,
            'media'   => 'all',
        ),

        'categories' => array(
            'src'     => 'assets/build/css/components/categories.min.css',
            'deps'    => array( 'app' ),
            'version' => null,
            'media'   => 'all',
        ),

        'footer' => array(
            'src'     => 'assets/build/css/components/footer.min.css',
            'deps'    => array( 'app' ),
            'version' => null,
            'media'   => 'all',
        ),

        'carousel' => array(
            'src'     => 'assets/build/css/components/carousel.min.css',
            'deps'    => array( 'app' ),
            'version' => null,
            'media'   => 'all',
        ),
    ),

    /*
     * ---------------------------------------------------------
     * Page Styles
     * ---------------------------------------------------------
     *
     * Loaded according to the current WordPress page context.
     */
    'pages' => array(

        'front-page' => array(
            'src'     => 'assets/build/css/pages/front-page.min.css',
            'deps'    => array( 'app' ),
            'version' => null,
            'media'   => 'all',
        ),

        'home' => array(
            'src'     => 'assets/build/css/pages/home.min.css',
            'deps'    => array( 'app' ),
            'version' => null,
            'media'   => 'all',
        ),

        'page' => array(
            'src'     => 'assets/build/css/pages/page.min.css',
            'deps'    => array( 'app' ),
            'version' => null,
            'media'   => 'all',
        ),

        'single' => array(
            'src'     => 'assets/build/css/pages/single.min.css',
            'deps'    => array( 'app' ),
            'version' => null,
            'media'   => 'all',
        ),

        'archive' => array(
            'src'     => 'assets/build/css/pages/archive.min.css',
            'deps'    => array( 'app' ),
            'version' => null,
            'media'   => 'all',
        ),

        'search' => array(
            'src'     => 'assets/build/css/pages/search.min.css',
            'deps'    => array( 'app' ),
            'version' => null,
            'media'   => 'all',
        ),

        '404' => array(
            'src'     => 'assets/build/css/pages/404.min.css',
            'deps'    => array( 'app' ),
            'version' => null,
            'media'   => 'all',
        ),
    ),

    /*
     * ---------------------------------------------------------
     * Editor Styles
     * ---------------------------------------------------------
     */
    'editor' => array(

        'styles' => array(

            'editor' => array(
                'src'     => 'assets/build/css/editor.min.css',
                'deps'    => array(),
                'version' => null,
                'media'   => 'all',
            ),
        ),

        'scripts' => array(),
    ),

    /*
     * ---------------------------------------------------------
     * Scripts
     * ---------------------------------------------------------
     */
    'scripts' => array(

        'app' => array(
            'src'       => 'assets/build/js/app.min.js',
            'deps'      => array( 'jquery' ),
            'version'   => null,
            'in_footer' => true,
        ),
    ),

    /*
     * ---------------------------------------------------------
     * Component Scripts
     * ---------------------------------------------------------
     */
    'component_scripts' => array(

        'carousel' => array(
            'src'       => 'assets/build/js/components/carousel.min.js',
            'deps'      => array( 'app' ),
            'version'   => null,
            'in_footer' => true,
        ),

        'navigation' => array(
            'src'       => 'assets/build/js/components/navigation.min.js',
            'deps'      => array( 'app' ),
            'version'   => null,
            'in_footer' => true,
        ),
    ),

    /*
     * ---------------------------------------------------------
     * Page Scripts
     * ---------------------------------------------------------
     */
    'page_scripts' => array(

        'front-page' => array(
            'src'       => 'assets/build/js/pages/front-page.min.js',
            'deps'      => array( 'app' ),
            'version'   => null,
            'in_footer' => true,
        ),

        'single' => array(
            'src'       => 'assets/build/js/pages/single.min.js',
            'deps'      => array( 'app' ),
            'version'   => null,
            'in_footer' => true,
        ),
    ),
);