<?php 

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
	'key' => 'group_69575b5433b00',
	'title' => 'Air Cooler Pricing',
	'fields' => array(
		array(
			'key' => 'field_69575b54369ce',
			'label' => 'Actual Price',
			'name' => 'actual_price',
			'aria-label' => '',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'acfe_settings' => '',
			'acfe_validate' => '',
			'min' => 0,
			'max' => '',
			'acfe_permissions' => '',
			'allow_in_bindings' => 0,
			'placeholder' => '',
			'step' => '0.01',
			'prepend' => '₹',
			'append' => '',
			'pll_default_value' => '',
		),
		array(
			'key' => 'field_69575b543a4d7',
			'label' => 'Final Price',
			'name' => 'final_price',
			'aria-label' => '',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'acfe_settings' => '',
			'acfe_validate' => '',
			'min' => 0,
			'max' => '',
			'acfe_permissions' => '',
			'allow_in_bindings' => 1,
			'placeholder' => '',
			'step' => '0.01',
			'prepend' => '₹',
			'append' => '',
			'pll_default_value' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'air_cooler',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'left',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 1,
	'display_title' => 'Product Pricing',
	'acfe_autosync' => array(
		0 => 'php',
		1 => 'json',
	),
	'acfe_permissions' => '',
	'acfe_form' => 1,
	'pll_display_field_instructions' => 1,
	'acfe_meta' => '',
	'acfe_note' => '',
	'modified' => 1768839295,
));

endif;