<?php
/**
 * WooShop Embeds Module
 *
 * Handles WordPress oEmbed behavior for the WooShop theme.
 * Keeps embedded content responsive, accessible, and lightweight.
 *
 * @package WooShop
 */

declare(strict_types=1);

namespace WooShop\Modules\Theme;

use WooShop\Core\Module;

defined('ABSPATH') || exit;

/**
 * Class Embeds
 *
 * Provides WooShop-specific oEmbed functionality.
 */
final class Embeds extends Module {

    /**
     * Register embed functionality.
     *
     * @return void
     */
    public function register(): void {

        add_filter(
            'oembed_result',
            [$this, 'filter_oembed_result'],
            10,
            3
        );

        add_filter(
            'oembed_dataparse',
            [$this, 'filter_oembed_data'],
            10,
            3
        );

        add_filter(
            'embed_oembed_html',
            [$this, 'filter_embed_html'],
            10,
            4
        );

        add_filter(
            'embed_thumbnail_image_shape',
            [$this, 'filter_thumbnail_shape']
        );
    }

    /**
     * Filter generated oEmbed HTML.
     *
     * Adds the WooShop embed wrapper and lazy-loading behavior
     * without modifying externally hosted embed resources.
     *
     * @param string $result    Generated embed HTML.
     * @param object $data      oEmbed response data.
     * @param string $url       Original embed URL.
     *
     * @return string
     */
    public function filter_oembed_result(
        string $result,
        object $data,
        string $url
    ): string {

        if ('' === trim($result)) {
            return $result;
        }

        /*
         * Do not process scripts or already wrapped content.
         */
        if (
            false !== strpos($result, 'wooshop-embed')
            || false !== stripos($result, '<script')
        ) {
            return $result;
        }

        return sprintf(
            '<div class="wooshop-embed embed-responsive">%s</div>',
            $result
        );
    }

    /**
     * Filter parsed oEmbed data.
     *
     * Ensures image embeds contain useful alternative text when
     * the provider supplies a title.
     *
     * @param string $return Parsed embed HTML.
     * @param object $data   oEmbed response data.
     * @param string $url    Original embed URL.
     *
     * @return string
     */
    public function filter_oembed_data(
        string $return,
        object $data,
        string $url
    ): string {

        if (
            isset($data->type)
            && 'photo' === $data->type
            && isset($data->title)
            && '' !== trim((string) $data->title)
            && false === stripos($return, 'alt=')
        ) {
            $return = preg_replace(
                '/<img\b/i',
                '<img alt="' .
                esc_attr(
                    (string) $data->title
                ) .
                '"',
                $return,
                1
            ) ?? $return;
        }

        return $return;
    }

    /**
     * Filter WordPress embed HTML.
     *
     * Adds a semantic WooShop wrapper around embeds generated by
     * the WordPress embed template.
     *
     * @param string $html      Embed HTML.
     * @param string $url       Embed URL.
     * @param array  $attr      Embed attributes.
     * @param int    $post_id   Post ID.
     *
     * @return string
     */
    public function filter_embed_html(
        string $html,
        string $url,
        array $attr,
        int $post_id
    ): string {

        if ('' === trim($html)) {
            return $html;
        }

        if (false !== strpos($html, 'wooshop-embed')) {
            return $html;
        }

        return sprintf(
            '<div class="wooshop-embed embed-responsive" data-embed-url="%s">%s</div>',
            esc_attr($url),
            $html
        );
    }

    /**
     * Configure the default embed thumbnail shape.
     *
     * @param string $shape Thumbnail shape.
     *
     * @return string
     */
    public function filter_thumbnail_shape(
        string $shape
    ): string {

        return 'square';
    }
}