<?php
/**
 * WooShop Asset Configuration
 *
 * Defines global, component, page, editor, admin, and
 * WooCommerce assets used by the WooShop Smart Asset Loader.
 *
 * Asset paths correspond directly to files generated by build.js.
 *
 * @package WooShop
 */

declare(strict_types=1);

defined('ABSPATH') || exit;

return array(

    /*
     * ---------------------------------------------------------
     * Frontend Assets
     * ---------------------------------------------------------
     */
    'frontend' => array(

        /*
         * Styles.
         */
        'styles' => array(

            /*
             * Main Bootstrap framework.
             */
            'bootstrap' => array(
                'src'     => 'assets/build/css/bootstrap.min.css',
                'deps'    => array(),
                'version' => null,
                'media'   => 'all',
            ),

            /*
             * Main WooShop application stylesheet.
             *
             * Contains global theme styling and compiled
             * Bootstrap customization where applicable.
             */
            'wooshop' => array(
                'src'     => 'assets/build/css/app.min.css',
                'deps'    => array('bootstrap'),
                'version' => null,
                'media'   => 'all',
            ),

        ),

        /*
         * Scripts.
         */
        'scripts' => array(

            /*
             * Main WooShop application JavaScript.
             */
            'wooshop' => array(
                'src'       => 'assets/build/js/app.min.js',
                'deps'      => array('jquery'),
                'version'   => null,
                'in_footer' => true,
                'strategy'  => 'defer',
            ),

        ),

    ),

    /*
     * ---------------------------------------------------------
     * Component Assets
     * ---------------------------------------------------------
     *
     * Components are loaded only when their conditions match.
     */
    'components' => array(

        'styles' => array(

            'header' => array(
                'src' => 'assets/build/css/components/header.min.css',
                'deps' => array('wooshop'),
            ),

            'navigation' => array(
                'src' => 'assets/build/css/components/navigation.min.css',
                'deps' => array('wooshop'),
            ),

            'product-card' => array(
                'src' => 'assets/build/css/components/product-card.min.css',
                'deps' => array('wooshop'),
            ),

            'product-grid' => array(
                'src' => 'assets/build/css/components/product-grid.min.css',
                'deps' => array('wooshop'),
            ),

            'carousel' => array(
                'src' => 'assets/build/css/components/carousel.min.css',
                'deps' => array('wooshop'),
            ),

            'offcanvas' => array(
                'src' => 'assets/build/css/components/offcanvas.min.css',
                'deps' => array('wooshop'),
            ),

            'modal' => array(
                'src' => 'assets/build/css/components/modal.min.css',
                'deps' => array('wooshop'),
            ),

            'forms' => array(
                'src' => 'assets/build/css/components/forms.min.css',
                'deps' => array('wooshop'),
            ),

        ),

        'scripts' => array(

            'header' => array(
                'src'       => 'assets/build/js/components/header.min.js',
                'deps'      => array('jquery'),
                'in_footer' => true,
                'strategy'  => 'defer',
            ),

            'navigation' => array(
                'src'       => 'assets/build/js/components/navigation.min.js',
                'deps'      => array('jquery'),
                'in_footer' => true,
                'strategy'  => 'defer',
            ),

            'carousel' => array(
                'src'       => 'assets/build/js/components/carousel.min.js',
                'deps'      => array(),
                'in_footer' => true,
                'strategy'  => 'defer',
            ),

            'offcanvas' => array(
                'src'       => 'assets/build/js/components/offcanvas.min.js',
                'deps'      => array(),
                'in_footer' => true,
                'strategy'  => 'defer',
            ),

            'modal' => array(
                'src'       => 'assets/build/js/components/modal.min.js',
                'deps'      => array(),
                'in_footer' => true,
                'strategy'  => 'defer',
            ),

        ),

    ),

    /*
     * ---------------------------------------------------------
     * Page Assets
     * ---------------------------------------------------------
     *
     * Loaded only on specific WordPress page contexts.
     */
    'pages' => array(

        'styles' => array(

            'home' => array(
                'src' => 'assets/build/css/pages/home.min.css',
                'deps' => array('wooshop'),
                'conditions' => array(
                    'is_home' => true,
                ),
            ),

            'front-page' => array(
                'src' => 'assets/build/css/pages/front-page.min.css',
                'deps' => array('wooshop'),
                'conditions' => array(
                    'is_front_page' => true,
                ),
            ),

            'shop' => array(
                'src' => 'assets/build/css/pages/shop.min.css',
                'deps' => array('wooshop'),
                'conditions' => array(
                    'is_shop' => true,
                ),
            ),

            'product' => array(
                'src' => 'assets/build/css/pages/product.min.css',
                'deps' => array('wooshop'),
                'conditions' => array(
                    'is_product' => true,
                ),
            ),

            'cart' => array(
                'src' => 'assets/build/css/pages/cart.min.css',
                'deps' => array('wooshop'),
                'conditions' => array(
                    'is_cart' => true,
                ),
            ),

            'checkout' => array(
                'src' => 'assets/build/css/pages/checkout.min.css',
                'deps' => array('wooshop'),
                'conditions' => array(
                    'is_checkout' => true,
                ),
            ),

            'account' => array(
                'src' => 'assets/build/css/pages/account.min.css',
                'deps' => array('wooshop'),
                'conditions' => array(
                    'is_account_page' => true,
                ),
            ),

        ),

        'scripts' => array(

            'home' => array(
                'src'       => 'assets/build/js/pages/home.min.js',
                'deps'      => array(),
                'in_footer' => true,
                'strategy'  => 'defer',
                'conditions' => array(
                    'is_home' => true,
                ),
            ),

            'front-page' => array(
                'src'       => 'assets/build/js/pages/front-page.min.js',
                'deps'      => array(),
                'in_footer' => true,
                'strategy'  => 'defer',
                'conditions' => array(
                    'is_front_page' => true,
                ),
            ),

            'shop' => array(
                'src'       => 'assets/build/js/pages/shop.min.js',
                'deps'      => array(),
                'in_footer' => true,
                'strategy'  => 'defer',
                'conditions' => array(
                    'is_shop' => true,
                ),
            ),

            'product' => array(
                'src'       => 'assets/build/js/pages/product.min.js',
                'deps'      => array(),
                'in_footer' => true,
                'strategy'  => 'defer',
                'conditions' => array(
                    'is_product' => true,
                ),
            ),

        ),

    ),

    /*
     * ---------------------------------------------------------
     * Editor Assets
     * ---------------------------------------------------------
     */
    'editor' => array(

        'styles' => array(

            'wooshop-editor' => array(
                'src'     => 'assets/build/css/editor.min.css',
                'deps'    => array(),
                'version' => null,
                'media'   => 'all',
            ),

        ),

        'scripts' => array(

            'wooshop-editor' => array(
                'src'       => 'assets/build/js/editor.min.js',
                'deps'      => array(),
                'in_footer' => true,
                'strategy'  => 'defer',
            ),

        ),

    ),

    /*
     * ---------------------------------------------------------
     * Admin Assets
     * ---------------------------------------------------------
     */
//    'admin' => array(
//
//        'styles' => array(
//
//            'wooshop-admin' => array(
//                'src'     => 'assets/build/css/admin.min.css',
//                'deps'    => array(),
//                'version' => null,
//                'media'   => 'all',
//            ),
//
//        ),
//
//        'scripts' => array(
//
//            'wooshop-admin' => array(
//                'src'       => 'assets/build/js/admin.min.js',
//                'deps'      => array(),
//                'in_footer' => true,
//                'strategy'  => 'defer',
//            ),
//
//        ),
//
//    ),

    /*
     * ---------------------------------------------------------
     * WooCommerce Assets
     * ---------------------------------------------------------
     *
     * Feature modules can reference these handles through
     * their own asset registration.
     */
    'woocommerce' => array(

        'styles' => array(

            'woocommerce' => array(
                'src' => 'assets/build/css/woocommerce.min.css',
                'deps' => array('wooshop'),
                'conditions' => array(
                    'is_woocommerce' => true,
                ),
            ),

        ),

        'scripts' => array(

            'woocommerce' => array(
                'src'       => 'assets/build/js/woocommerce.min.js',
                'deps'      => array('jquery'),
                'in_footer' => true,
                'strategy'  => 'defer',
                'conditions' => array(
                    'is_woocommerce' => true,
                ),
            ),

        ),

    ),

);